version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: on-failure:3
    ports:
      - "3080:3000"
    env_file: .env
    environment:
      - MONGODB_URI=mongodb://${MONGO_BOT_USER}:${MONGO_BOT_PASSWORD}@mongo:27017/bot?authSource=bot
    depends_on:
      mongo:
        condition: service_started
    volumes:
      - ./gcp-key.json:/app/gcp-key.json:ro
    networks:
      - bot
  mongo:
    image: mongo:8.0
    restart: on-failure:3
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_BOT_USER=${MONGO_BOT_USER}
      - MONGO_BOT_PASSWORD=${MONGO_BOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./cd/mongo/init-bot-database.sh:/docker-entrypoint-initdb.d/init-bot-database.sh:ro
    networks:
      - bot

networks:
  bot:
    driver: bridge
    attachable: true

volumes:
  mongo-data:
